import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { QuizSet } from './entities/quiz-set.entity';
import { QuizQuestion } from '../quiz-questions/entities/quiz-question.entity';
import { QuizAnswer } from '../quiz-answers/entities/quiz-answer.entity';
import { Note } from '../notes/entities/note.entity';
import { NoteBlock } from '../note-blocks/entities/note-block.entity';
import { CreateQuizSetDto, UpdateQuizSetDto, ManualQuizSetDto, MergeQuizSetsDto } from './dto/quiz-set.dto';
import { GeminiService } from '../common/llm/gemini.service';
import { AiUsageService } from '../ai-usage/ai-usage.service';

@Injectable()
export class QuizSetsService {
  constructor(
    @InjectRepository(QuizSet)
    private quizSetRepository: Repository<QuizSet>,

    @InjectRepository(QuizQuestion)
    private questionRepo: Repository<QuizQuestion>,

    @InjectRepository(QuizAnswer)
    private answerRepo: Repository<QuizAnswer>,

    @InjectRepository(Note)
    private noteRepo: Repository<Note>,

    @InjectRepository(NoteBlock)
    private blockRepo: Repository<NoteBlock>,

    private readonly geminiService: GeminiService,
    private readonly aiUsageService: AiUsageService,
  ) {}

  async generateFromNote(
    noteId: string,
    userId: string,
    options?: {
      count?: number;
      minCount?: number;
      language?: 'th' | 'en';
      questionTypes?: ('multiple_choice' | 'true_false' | 'short_answer')[];
    },
  ) {
    const note = await this.noteRepo.findOne({
      where: { id: noteId, userId },
    });

    if (!note) {
      throw new NotFoundException('Note not found');
    }

    const blocks = await this.blockRepo.find({
      where: { noteId },
      order: { position: 'ASC' },
    });

    const content = blocks
      .map(b => b.content?.text ?? '')
      .join('\n');

    if (!content.trim()) {
      throw new BadRequestException('Note is empty');
    }

    const set = this.quizSetRepository.create({
      note: { id: noteId },
      title: `Quiz from ${note.title}`,
      description: 'Generated by Gemini',
    });
    await this.quizSetRepository.save(set);

    const language = options?.language ?? 'th';
    const questionTypes = options?.questionTypes ?? ['multiple_choice', 'true_false'];

    const countRule = options?.count
      ? `Create exactly ${options.count} questions.`
      : `Create at least ${options?.minCount ?? 5} questions.`;

    const prompt = `
You are an expert educational content creator specializing in quiz generation.

${countRule}

Notes:
${content}

Requirements:
- Create a mix of question types: ${questionTypes.join(', ')}
- Language: ${language === 'th' ? 'Thai' : 'English'}
- Each question should test understanding of the material
- Multiple choice questions should have 4 options (A, B, C, D)
- Include explanations for correct answers

IMPORTANT:
Return ONLY valid JSON.

Format:
[
  {
    "question_text": "The question text",
    "question_type": "multiple_choice",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correct_answer": "Option A",
    "explanation": "Explanation why this is correct"
  },
  {
    "question_text": "True or false statement",
    "question_type": "true_false",
    "options": null,
    "correct_answer": "True",
    "explanation": "Explanation"
  }
]
`;

    await this.aiUsageService.increment(userId);
    const llmText = await this.geminiService.generate(prompt);
    const jsonStart = llmText.indexOf('[');
    const jsonEnd = llmText.lastIndexOf(']');

    if (jsonStart === -1 || jsonEnd === -1) {
      throw new BadRequestException('LLM did not return JSON');
    }

    const jsonString = llmText.slice(jsonStart, jsonEnd + 1);

    let questions;
    try {
      questions = JSON.parse(jsonString);
    } catch (e) {
      console.error('LLM raw response:', llmText);
      throw new BadRequestException('Invalid LLM response');
    }

    if (!Array.isArray(questions) || questions.length === 0) {
      throw new BadRequestException('No quiz questions generated');
    }

    await this.questionRepo.save(
      questions.map(q =>
        this.questionRepo.create({
          quiz_set_id: set.id,
          question_text: q.question_text,
          question_type: q.question_type,
          options: q.options,
          correct_answer: q.correct_answer,
          explanation: q.explanation,
        }),
      ),
    );

    note.hasQuiz = true;
    await this.noteRepo.save(note);

    return {
      setId: set.id,
      count: questions.length,
    };
  }

  async createManual(dto: ManualQuizSetDto, userId: string): Promise<{ setId: string; count: number }> {
    const note = await this.noteRepo.findOne({ where: { id: dto.noteId, userId } });
    if (!note) throw new NotFoundException('Note not found');
    if (!dto.questions || dto.questions.length === 0) {
      throw new BadRequestException('At least one question is required');
    }

    const set = this.quizSetRepository.create({
      note: { id: dto.noteId },
      title: dto.title || 'Manual Quiz',
      description: dto.description || 'Manually created',
    });
    await this.quizSetRepository.save(set);

    await this.questionRepo.save(
      dto.questions.map(q => this.questionRepo.create({ ...q, quiz_set_id: set.id })),
    );

    note.hasQuiz = true;
    await this.noteRepo.save(note);
    return { setId: set.id, count: dto.questions.length };
  }

  async mergeFromSets(dto: MergeQuizSetsDto, userId: string): Promise<{ setId: string; count: number }> {
    const note = await this.noteRepo.findOne({ where: { id: dto.noteId, userId } });
    if (!note) throw new NotFoundException('Note not found');
    if (!dto.sourceSetIds || dto.sourceSetIds.length === 0) {
      throw new BadRequestException('At least one source set is required');
    }

    const questions = await this.questionRepo.find({
      where: { quiz_set_id: In(dto.sourceSetIds) },
    });

    const set = this.quizSetRepository.create({
      note: { id: dto.noteId },
      title: dto.title || 'Merged Quiz',
      description: 'Merged from multiple sets',
    });
    await this.quizSetRepository.save(set);

    if (questions.length > 0) {
      await this.questionRepo.save(
        questions.map(q => this.questionRepo.create({
          quiz_set_id: set.id,
          question_text: q.question_text,
          question_type: q.question_type,
          options: q.options,
          correct_answer: q.correct_answer,
          explanation: q.explanation,
        })),
      );
    }

    note.hasQuiz = true;
    await this.noteRepo.save(note);
    return { setId: set.id, count: questions.length };
  }

  async mergeWrongAnswers(dto: MergeQuizSetsDto, userId: string): Promise<{ setId: string; count: number }> {
    const note = await this.noteRepo.findOne({ where: { id: dto.noteId, userId } });
    if (!note) throw new NotFoundException('Note not found');
    if (!dto.sourceSetIds || dto.sourceSetIds.length === 0) {
      throw new BadRequestException('At least one source set is required');
    }

    const wrongAnswers = await this.answerRepo.find({
      where: {
        isCorrect: false,
        question: { quiz_set_id: In(dto.sourceSetIds) },
      },
      relations: ['question'],
    });

    const uniqueQuestions = Array.from(
      new Map(wrongAnswers.map(a => [a.question_id, a.question])).values(),
    );

    const set = this.quizSetRepository.create({
      note: { id: dto.noteId },
      title: dto.title || 'Wrong Answers Review',
      description: 'Questions you answered incorrectly',
    });
    await this.quizSetRepository.save(set);

    if (uniqueQuestions.length > 0) {
      await this.questionRepo.save(
        uniqueQuestions.map(q => this.questionRepo.create({
          quiz_set_id: set.id,
          question_text: q.question_text,
          question_type: q.question_type,
          options: q.options,
          correct_answer: q.correct_answer,
          explanation: q.explanation,
        })),
      );
    }

    note.hasQuiz = true;
    await this.noteRepo.save(note);
    return { setId: set.id, count: uniqueQuestions.length };
  }

  async create(createQuizSetDto: CreateQuizSetDto): Promise<QuizSet> {
    const quizSet = this.quizSetRepository.create(createQuizSetDto);
    return await this.quizSetRepository.save(quizSet);
  }

  async findAll(): Promise<QuizSet[]> {
    return await this.quizSetRepository.find({
      where: { isDeleted: false },
      relations: ['questions'],
    });
  }

  async findOne(id: string): Promise<QuizSet | null> {
    return await this.quizSetRepository.findOne({
      where: { id, isDeleted: false },
      relations: ['questions'],
    });
  }

  async findByNoteId(noteId: string): Promise<QuizSet[]> {
    return await this.quizSetRepository.find({
      where: { note_id: noteId, isDeleted: false },
      relations: ['questions'],
    });
  }

  async update(id: string, updateQuizSetDto: UpdateQuizSetDto): Promise<QuizSet | null> {
    await this.quizSetRepository.update(id, updateQuizSetDto);
    return this.findOne(id);
  }

  async remove(id: string): Promise<void> {
    await this.quizSetRepository.update(id, {
      isDeleted: true,
      deletedAt: new Date(),
    });
    // Sync hasQuiz flag on the note
    const set = await this.quizSetRepository.findOne({
      where: { id },
      relations: ['note'],
    });
    if (set?.note) {
      await this.syncNoteHasQuiz(set.note.id);
    }
  }

  async restore(id: string, userId: string): Promise<QuizSet> {
    const set = await this.quizSetRepository.findOne({
      where: { id, isDeleted: true, note: { userId } },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Deleted quiz set not found');
    }

    set.isDeleted = false;
    set.deletedAt = null;
    const saved = await this.quizSetRepository.save(set);
    await this.syncNoteHasQuiz(set.note.id);
    return saved;
  }

  async hardDelete(id: string, userId: string): Promise<void> {
    const set = await this.quizSetRepository.findOne({
      where: { id, isDeleted: true, note: { userId } },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Deleted quiz set not found');
    }

    await this.quizSetRepository.remove(set);
  }

  async findDeleted(userId: string): Promise<QuizSet[]> {
    // Auto-cleanup sets deleted more than 30 days ago
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    await this.quizSetRepository
      .createQueryBuilder()
      .delete()
      .from(QuizSet)
      .where('is_deleted = true AND deleted_at IS NOT NULL AND deleted_at < :cutoff', {
        cutoff: thirtyDaysAgo,
      })
      .execute();

    return this.quizSetRepository.find({
      where: { isDeleted: true, note: { userId } },
      relations: ['note'],
      order: { deletedAt: 'DESC' },
    });
  }

  private async syncNoteHasQuiz(noteId: string) {
    const count = await this.quizSetRepository.count({
      where: {
        note: { id: noteId },
        isDeleted: false,
      },
    });

    await this.noteRepo.update(
      { id: noteId },
      { hasQuiz: count > 0 },
    );
  }
}
