import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { FlashcardSet } from './entities/flashcard-set.entity';
import { Flashcard } from '../flashcards/entities/flashcards.entity';
import { Note } from '../notes/entities/note.entity';
import { NoteBlock } from '../note-blocks/entities/note-block.entity';
import { GeminiService } from '../common/llm/gemini.service';

@Injectable()
export class FlashcardSetsService {
  constructor(
    @InjectRepository(FlashcardSet)
    private readonly setRepo: Repository<FlashcardSet>,

    @InjectRepository(Flashcard)
    private readonly cardRepo: Repository<Flashcard>,

    @InjectRepository(Note)
    private readonly noteRepo: Repository<Note>,

    @InjectRepository(NoteBlock)
    private readonly blockRepo: Repository<NoteBlock>,

    private readonly geminiService: GeminiService,
  ) {}

  async generateFromNote(
    noteId: string,
    userId: string,
    options?: {
      count?: number;
      minCount?: number;
      language?: 'th' | 'en';
    },
  ) {
    const note = await this.noteRepo.findOne({
      where: { id: noteId, userId },
    });

    if (!note) {
      throw new NotFoundException('Note not found');
    }

    const blocks = await this.blockRepo.find({
      where: { noteId },
      order: { position: 'ASC' },
    });

    const content = blocks
      .map(b => b.content?.text ?? '')
      .join('\n');

    if (!content.trim()) {
      throw new BadRequestException('Note is empty');
    }

    const set = this.setRepo.create({
      note: { id: noteId },
      title: `Flashcards from ${note.title}`,
      description: 'Generated by Gemini',
    });
    await this.setRepo.save(set);

    const language = options?.language ?? 'th';

    const countRule = options?.count
      ? `Create exactly ${options.count} flashcards.`
      : `Create at least ${options?.minCount ?? 5} flashcards.`;

    const prompt = `
You are an expert educational content creator.

${countRule}

Notes:
${content}

Requirements:
- Front: A clear question
- Back: A detailed answer
- Language: ${language === 'th' ? 'Thai' : 'English'}

IMPORTANT:
Return ONLY valid JSON.

Format:
[
  {
    "front_text": "question",
    "back_text": "answer or short explanation"
  }
]
`;

    const llmText = await this.geminiService.generate(prompt);
    const jsonStart = llmText.indexOf('[');
    const jsonEnd = llmText.lastIndexOf(']');

    if (jsonStart === -1 || jsonEnd === -1) {
      throw new BadRequestException('LLM did not return JSON');
    }

    const jsonString = llmText.slice(jsonStart, jsonEnd + 1);

    let cards;
    try {
      cards = JSON.parse(jsonString);
    } catch (e) {
      console.error('LLM raw response:', llmText);
      throw new BadRequestException('Invalid LLM response');
    }


    if (!Array.isArray(cards) || cards.length === 0) {
      throw new BadRequestException('No flashcards generated');
    }

    await this.cardRepo.save(
      cards.map(c =>
        this.cardRepo.create({
          set_id: set.id,
          front_text: c.front_text,
          back_text: c.back_text,
        }),
      ),
    );

    if (!note) {
      throw new NotFoundException('Note not found');
    }

    note.hasFlashcard = true;
    await this.noteRepo.save(note);

    return {
      setId: set.id,
      count: cards.length,
    };
  }

  async findByNote(noteId: string) {
    return this.setRepo.find({
      where: {
        note: { id: noteId },
        isDeleted: false,
      },
      order: { created_at: 'DESC' },
    });
  }

  async findOne(setId: string) {
    const set = await this.setRepo.findOne({
      where: { id: setId },
      relations: ['flashcards'],
    });

    if (!set) {
      throw new NotFoundException('Flashcard set not found');
    }

    return set;
  }

  async remove(setId: string, userId: string) {
    const set = await this.setRepo.findOne({
      where: {
        id: setId,
        note: { userId },
        isDeleted: false,
      },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Flashcard set not found');
    }

    set.isDeleted = true;
    await this.setRepo.save(set);

    return { success: true };
  }

  async restore(setId: string, userId: string) {
    const set = await this.setRepo.findOne({
      where: {
        id: setId,
        isDeleted: true,
        note: { userId },
      },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Deleted flashcard set not found');
    }

    set.isDeleted = false;
    return this.setRepo.save(set);
  }

  async hardDelete(id: string): Promise<void> {
    const set = await this.findOne(id);
    await this.setRepo.remove(set);
  }
}