import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { FlashcardSet } from './entities/flashcard-set.entity';
import { Flashcard } from '../flashcards/entities/flashcards.entity';
import { FlashcardReview } from '../flashcard-reviews/entities/flashcard-review.entity';
import { Note } from '../notes/entities/note.entity';
import { NoteBlock } from '../note-blocks/entities/note-block.entity';
import { GeminiService } from '../common/llm/gemini.service';
import { CreateManualFlashcardSetDto, MergeFlashcardSetsDto } from './dto/flashcard-set.dto';
import { AiUsageService } from '../ai-usage/ai-usage.service';

@Injectable()
export class FlashcardSetsService {
  constructor(
    @InjectRepository(FlashcardSet)
    private readonly setRepo: Repository<FlashcardSet>,

    @InjectRepository(Flashcard)
    private readonly cardRepo: Repository<Flashcard>,

    @InjectRepository(FlashcardReview)
    private readonly reviewRepo: Repository<FlashcardReview>,

    @InjectRepository(Note)
    private readonly noteRepo: Repository<Note>,

    @InjectRepository(NoteBlock)
    private readonly blockRepo: Repository<NoteBlock>,

    private readonly geminiService: GeminiService,
    private readonly aiUsageService: AiUsageService,
  ) {}

  async generateFromNote(
    noteId: string,
    userId: string,
    options?: {
      count?: number;
      minCount?: number;
      language?: 'th' | 'en';
    },
  ) {
    const note = await this.noteRepo.findOne({
      where: { id: noteId, userId },
    });

    if (!note) {
      throw new NotFoundException('Note not found');
    }

    const blocks = await this.blockRepo.find({
      where: { noteId },
      order: { position: 'ASC' },
    });

    const content = blocks
      .map(b => b.content?.text ?? '')
      .join('\n');

    if (!content.trim()) {
      throw new BadRequestException('Note is empty');
    }

    const set = this.setRepo.create({
      note: { id: noteId },
      title: `Flashcards from ${note.title}`,
      description: 'Generated by Gemini',
    });
    await this.setRepo.save(set);

    const language = options?.language ?? 'th';

    const countRule = options?.count
      ? `Create exactly ${options.count} flashcards.`
      : `Create at least ${options?.minCount ?? 5} flashcards.`;

    const prompt = `
You are an expert educational content creator.

${countRule}

Notes:
${content}

Requirements:
- Front: A clear question
- Back: A detailed answer
- Language: ${language === 'th' ? 'Thai' : 'English'}

IMPORTANT:
Return ONLY valid JSON.

Format:
[
  {
    "front_text": "question",
    "back_text": "answer or short explanation"
  }
]
`;

    await this.aiUsageService.increment(userId);
    const llmText = await this.geminiService.generate(prompt);
    const jsonStart = llmText.indexOf('[');
    const jsonEnd = llmText.lastIndexOf(']');

    if (jsonStart === -1 || jsonEnd === -1) {
      throw new BadRequestException('LLM did not return JSON');
    }

    const jsonString = llmText.slice(jsonStart, jsonEnd + 1);

    let cards;
    try {
      cards = JSON.parse(jsonString);
    } catch (e) {
      console.error('LLM raw response:', llmText);
      throw new BadRequestException('Invalid LLM response');
    }


    if (!Array.isArray(cards) || cards.length === 0) {
      throw new BadRequestException('No flashcards generated');
    }

    await this.cardRepo.save(
      cards.map(c =>
        this.cardRepo.create({
          set_id: set.id,
          front_text: c.front_text,
          back_text: c.back_text,
        }),
      ),
    );

    if (!note) {
      throw new NotFoundException('Note not found');
    }

    note.hasFlashcard = true;
    await this.noteRepo.save(note);

    return {
      setId: set.id,
      count: cards.length,
    };
  }

  async findByNote(noteId: string) {
    return this.setRepo.createQueryBuilder('set')
      .where('set.note_id = :noteId', { noteId })
      .andWhere('set.is_deleted = false')
      .loadRelationCountAndMap('set.cardCount', 'set.flashcards')
      .orderBy('set.created_at', 'DESC')
      .getMany();
  }

  async findOne(setId: string) {
    const set = await this.setRepo.findOne({
      where: { id: setId },
      relations: ['flashcards'],
    });

    if (!set) {
      throw new NotFoundException('Flashcard set not found');
    }

    return set;
  }

  async update(setId: string, userId: string, dto: { title?: string; description?: string }) {
    const set = await this.setRepo.findOne({
      where: { id: setId, note: { userId }, isDeleted: false },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Flashcard set not found');
    }

    if (dto.title !== undefined) set.title = dto.title;
    if (dto.description !== undefined) set.description = dto.description;

    return this.setRepo.save(set);
  }

  async remove(setId: string, userId: string) {
    const set = await this.setRepo.findOne({
      where: {
        id: setId,
        note: { userId },
        isDeleted: false,
      },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Flashcard set not found');
    }

    set.isDeleted = true;
    set.deletedAt = new Date();
    await this.setRepo.save(set);
    await this.syncNoteHasFlashcard(set.note.id);

    return { success: true };
  }

  async restore(setId: string, userId: string) {
    const set = await this.setRepo.findOne({
      where: {
        id: setId,
        isDeleted: true,
        note: { userId },
      },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Deleted flashcard set not found');
    }

    set.isDeleted = false;
    set.deletedAt = null;
    await this.syncNoteHasFlashcard(set.note.id);
    return this.setRepo.save(set);
  }

  async hardDelete(id: string, userId: string): Promise<void> {
    const set = await this.setRepo.findOne({
      where: { id, isDeleted: true, note: { userId } },
      relations: ['note'],
    });

    if (!set) {
      throw new NotFoundException('Deleted flashcard set not found');
    }

    await this.setRepo.remove(set);
  }

  async findDeleted(userId: string) {
    // Auto-cleanup sets deleted more than 30 days ago
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    await this.setRepo
      .createQueryBuilder()
      .delete()
      .from(FlashcardSet)
      .where('is_deleted = true AND deleted_at IS NOT NULL AND deleted_at < :cutoff', {
        cutoff: thirtyDaysAgo,
      })
      .execute();

    return this.setRepo.find({
      where: { isDeleted: true, note: { userId } },
      relations: ['note'],
      order: { deletedAt: 'DESC' },
    });
  }

  async createManual(dto: CreateManualFlashcardSetDto, userId: string) {
    const note = await this.noteRepo.findOne({
      where: { id: dto.noteId, userId },
    });
    if (!note) throw new NotFoundException('Note not found');

    if (!dto.cards || dto.cards.length === 0) {
      throw new BadRequestException('At least one card is required');
    }

    const set = this.setRepo.create({
      note: { id: dto.noteId },
      title: dto.title || 'Manual Flashcards',
      description: 'Manually created',
    });
    await this.setRepo.save(set);

    await this.cardRepo.save(
      dto.cards.map(c =>
        this.cardRepo.create({
          set_id: set.id,
          front_text: c.front_text,
          back_text: c.back_text,
        }),
      ),
    );

    note.hasFlashcard = true;
    await this.noteRepo.save(note);

    return { setId: set.id, count: dto.cards.length };
  }

  async mergeFromSets(dto: MergeFlashcardSetsDto, userId: string) {
    const note = await this.noteRepo.findOne({
      where: { id: dto.noteId, userId },
    });
    if (!note) throw new NotFoundException('Note not found');

    if (!dto.sourceSetIds || dto.sourceSetIds.length === 0) {
      throw new BadRequestException('At least one source set is required');
    }

    const cards = await this.cardRepo.find({
      where: { set_id: In(dto.sourceSetIds) },
    });

    const set = this.setRepo.create({
      note: { id: dto.noteId },
      title: dto.title || 'Merged Flashcards',
      description: 'Merged from multiple sets',
    });
    await this.setRepo.save(set);

    if (cards.length > 0) {
      await this.cardRepo.save(
        cards.map(c =>
          this.cardRepo.create({
            set_id: set.id,
            front_text: c.front_text,
            back_text: c.back_text,
          }),
        ),
      );
    }

    note.hasFlashcard = true;
    await this.noteRepo.save(note);

    return { setId: set.id, count: cards.length };
  }

  async mergeWrongAnswers(dto: MergeFlashcardSetsDto, userId: string) {
    const note = await this.noteRepo.findOne({
      where: { id: dto.noteId, userId },
    });
    if (!note) throw new NotFoundException('Note not found');

    if (!dto.sourceSetIds || dto.sourceSetIds.length === 0) {
      throw new BadRequestException('At least one source set is required');
    }

    const wrongReviews = await this.reviewRepo
      .createQueryBuilder('review')
      .innerJoinAndSelect('review.flashcard', 'flashcard')
      .where('flashcard.set_id IN (:...setIds)', { setIds: dto.sourceSetIds })
      .andWhere('review.isCorrect = :correct', { correct: false })
      .getMany();

    const flashcardMap = new Map<string, { front_text: string; back_text: string }>();
    for (const review of wrongReviews) {
      if (!flashcardMap.has(review.flashcard.id)) {
        flashcardMap.set(review.flashcard.id, {
          front_text: review.flashcard.front_text,
          back_text: review.flashcard.back_text,
        });
      }
    }
    const cards = [...flashcardMap.values()];

    const set = this.setRepo.create({
      note: { id: dto.noteId },
      title: dto.title || 'Wrong Answers Review',
      description: 'Cards you answered incorrectly',
    });
    await this.setRepo.save(set);

    if (cards.length > 0) {
      await this.cardRepo.save(
        cards.map(c =>
          this.cardRepo.create({
            set_id: set.id,
            front_text: c.front_text,
            back_text: c.back_text,
          }),
        ),
      );
    }

    note.hasFlashcard = true;
    await this.noteRepo.save(note);

    return { setId: set.id, count: cards.length };
  }

  private async syncNoteHasFlashcard(noteId: string) {
    const count = await this.setRepo.count({
      where: {
        note: { id: noteId },
        isDeleted: false,
      },
    });

    await this.noteRepo.update(
      { id: noteId },
      { hasFlashcard: count > 0 },
    );
  }
}